### ISSUE TITLE
Add RNG & expand site list.

### ISSUE THREAD

**Issue by ELKER54** [FelixKLG/tabby-cat#1]
There needs to be videos that play so it's a bunch of moaning.

**Comment by DannDev1** [comment]
I approve

**Comment by FelixKLG** [comment]
Which links would you suggest?
Also how do you suggest implementing a limit to avoid overloading the client too much?

**Comment by DannDev1** [comment]
More websites but not just linking to the gay portion - Example listed below.
https://github.com/emanuelmiranda83/porn-site-list/blob/master/sites.json

Additionally, I would suggest having a random interval between 1 minute - to - 1 hour that it would open one of these sites with the process being hidden preferably.

**Comment by FelixKLG** [comment]
On Windows I can use the Windows crate to interface with the WinAPI to hide the window and install it as a service.
https://docs.rs/windows-sys/latest/windows_sys/Win32/UI/WindowsAndMessaging/fn.ShowWindow.html
https://learn.microsoft.com/en-us/windows/win32/api/winsvc/

Aside from that I like the random interval idea; it removed the bottleneck that is seen by spamming open masses of tabs and confuses the user a lot more.

**Comment by FelixKLG** [comment]
Update: last night I spent a couple of hours messing aroung with the Windows crate and found out how to hide the actual window; now I have two options for the alternate URLs:

1. I embed the URLs in the code
2. I link to an external JSON resource

Additionally would such resources need encrypting to prevent request sniffing and what would be the most feasable hosting system for such list.

**Comment by ELKER54** [comment]
Thanks!

**Comment by FelixKLG** [comment]
This has been achieved in e11da477efd78a45920af8c5280e9063af579301, there is now an array of locally stored string to avoid a massive binary involved with fetching it remotely.
Additionally, the choice of site to open is entirely random.
