### ISSUE TITLE
Prevent redistribution

### ISSUE THREAD

**Issue by FelixKLG** [FelixKLG/tabby-cat#2]
Idealy as this software can be used rather maliciously I would like to be able to control who has access to redistribute it.
This will likely involve me creating a back-end DRM to prevent people with bad intent from using this to harm others.

**Comment by judas-js** [comment]
shut up nerd /hj

**Comment by FelixKLG** [comment]
> shut up nerd /hj

Shut yo bitch ass up

**Comment by judas-js** [comment]
> > shut up nerd /hj
> 
> Shut yo bitch ass up

i will threaten multiple slurs at you home of sexual

**Comment by sneakyspeedyboii** [comment]
when ran, run in background, add to boot, grab hwid and store in database where authenticated users can access the website and approve it being ran on different devices, and allows a toggle to run or not
