### ISSUE TITLE
Does not add itself to boot

### ISSUE THREAD

**Issue by sneakyspeedyboii** [FelixKLG/tabby-cat#3]
Does not add to boot, when start up on boot, when immense trolling

**Comment by FelixKLG** [comment]
Good point, this will be easiest on Windows and Linux not so on MacOS.

Copying to the startup dir and adding to systemd wouldn't be difficult.

**Comment by sneakyspeedyboii** [comment]
[Intro]
[Aye man, it's your boy Lil B](https://genius.com/26480355/Lil-b-swag-like-ohio/Aye-man-its-your-boy-lil-b)

[Verse 1]
[Down in Ohio](https://genius.com/26408691/Lil-b-swag-like-ohio/Down-in-ohio) (Swag), fuckin' all these bitches
(Swag, swag, swag)
Drinkin' coleridge, swag so saucy (Oh, oh, oh)
[Posted in Cleveland, drive to Columbus](https://genius.com/26958697/Lil-b-swag-like-ohio/Posted-in-cleveland-drive-to-columbus) (Oh, oh)
[Bitches suck my dick, 'cause my swag on a hundred](https://genius.com/26221563/Lil-b-swag-like-ohio/Bitches-suck-my-dick-cause-my-swag-on-a-hundred)
(Oh, oh, oh, oh, oh)
[Chorus]
[Down in Ohio, swag like Ohio](https://genius.com/26927164/Lil-b-swag-like-ohio/Down-in-ohio-swag-like-ohio)
[Down in Ohio (Oh), swag like Ohio](https://genius.com/26716743/Lil-b-swag-like-ohio/Down-in-ohio-oh-swag-like-ohio) (Swag)
Down in Ohio (Oh, oh), swag like Ohio
Down in Ohio, swag like Ohio

[Verse 2]
Bitch I'm rich, I give a fuck
Real nigga, gold grill
[Ten thousand, no deal](https://genius.com/26480370/Lil-b-swag-like-ohio/Ten-thousand-no-deal)
[No single, just me](https://genius.com/27091600/Lil-b-swag-like-ohio/No-single-just-me)
[Thirty thousand, for a feature](https://genius.com/26480396/Lil-b-swag-like-ohio/Thirty-thousand-for-a-feature)
[Hood niggas, ten thousand](https://genius.com/26885678/Lil-b-swag-like-ohio/Hood-niggas-ten-thousand)
BasedGod, hood bitch call me daddy
[Where you from? I got love for Cincinnati, Ohio](https://genius.com/26480336/Lil-b-swag-like-ohio/Where-you-from-i-got-love-for-cincinnati-ohio)

[Chorus]
[Down in Ohio, swag like Ohio](https://genius.com/27005847/Lil-b-swag-like-ohio/Down-in-ohio-swag-like-ohio)
Down in Ohio, swag like Ohio
Down in Ohio, swag like Ohio
Down in Ohio, swag like Ohio
[Ohio, throw that shit up](https://genius.com/26958754/Lil-b-swag-like-ohio/Ohio-throw-that-shit-up)

[Bridge]
Ohio, throw that shit up, you feel me
[Dayton, Ohio, Columbus, Cincinnati, Cleveland](https://genius.com/26001790/Lil-b-swag-like-ohio/Dayton-ohio-columbus-cincinnati-cleveland)
[Throw that shit up man it's way more spots](https://genius.com/26885697/Lil-b-swag-like-ohio/Throw-that-shit-up-man-its-way-more-spots)
If you from Ohio throw that shit up
You feel me, fuck bitches to this, get money 'n this
Cook to this, BasedGod for life
I'm based for life, showin' that love
I'm swaggin' like Ohio, you feel me (woo)
You might also like
Swag on My Dick
Lil B
Swag Jerry Rice
Lil B
Wonton Soup
Lil B
[Chorus]
Down in Ohio, swag like Ohio
Down in Ohio, swag like Ohio
Down in Ohio, swag like Ohio
Down in Ohio, swag like Ohio

**Comment by sneakyspeedyboii** [comment]
what disruptive content, never
